[package]
name = "tiktok-matrix"
version = "0.0.5"
description = "TikTok Matrix System by niostack.com"
authors = ["niostack"]
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
tauri = { version = "1.5", features = ["app-all", "shell-open"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
local-ip-address = "0.5.6"
tungstenite = "0.13.0"
tokio-tungstenite = "0.15.0"
futures-util = "0.3.17"
tokio = { version = "1", features = ["full"] }
pickledb = "0.5.1"
machine-uid = "0.5.1"
reqwest = { version = "0.11", features = ["blocking", "multipart", "json"] }


[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
