name: Release
run-name: ${{ github.actor }} is building Release 🚀
on:
  push:
    branches:
      - release
jobs:
  deploy:
    runs-on: windows-latest
    strategy:
      fail-fast: true
    steps:  
      - name: Checkout main repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for full submodule history
      - name: Set up Git environment
        run: |
          git config --global user.email "niostack@gmail.com"
          git config --global user.name "ciuser"
          set GIT_TERMINAL_PROMPT=0
      - name: Initialize and update submodules
        run: |
          git submodule update --init --recursive
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: setup rust
        uses: dtolnay/rust-toolchain@stable
      - name: build
        run: |
          npm install
          npm run build:tiktok-agent
          .\build.ps1
      - name: commit
        run: |
          git add -A
          git commit -m "Release"
          git push
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: ./src-tauri/target/release/bundled/msi/*

      