name: Release
run-name: ${{ github.actor }} is building Release 🚀
on:
  push:
    branches:
      - release
jobs:
  deploy:
    runs-on: windows-latest
    strategy:
      fail-fast: true
    steps:  
      - name: Checkout main repository
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: setup rust
        uses: dtolnay/rust-toolchain@stable
      - name: build
        run: |
          npm install
          .\build.ps1
      - name: commit
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "Release"
          git push
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: ./src-tauri/target/release/bundled/msi/*

      